# Basic knowledge about numpy

### 1.ndarray features

#### (1)multi-dimensional

In [ ]:
from tracemalloc import Statistic
import numpy as np
from numpy.ma.extras import column_stack

In [ ]:
arr=np.array(5)    #create zero dimension array
print(arr)
print("Dimension of arr:",arr.ndim)

In [3]:
arr=np.array([1,2,3])
print(arr)
print("Dimension of arr:",arr.ndim)

[1 2 3]
Dimension of arr: 1


In [5]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("Dimension of arr:",arr.ndim)

[[1 2 3]
 [4 5 6]]
Dimension of arr: 2


#### (2)Homogenity

In [6]:
arr=np.array([1,'hello'])  #different data types will be converted into the same type, 1 is turned into string type
print(arr)

['1' 'hello']


In [7]:
arr=np.array([1,2.5]) # 1 is turned into float
print(arr)

[1.  2.5]


### 2.ndarray attribute

In [14]:
arr=np.array([1,2,3])
print(arr)
print('shape:',arr.shape)   #expressed as a tuple
print('dimension:',arr.ndim)
print('size:',arr.size)
print('data type:',arr.dtype)

[1 2 3]
shape: (3,)
dimension: 1
size: 3
data type: int64


In [15]:
arr=np.array([[1.5,2,3],[4,5,6]])
print(arr)
print('shape:',arr.shape)   #expressed as a tuple
print('dimension:',arr.ndim)
print('size:',arr.size)
print('data type:',arr.dtype)
print('the transfered matrix of the original:',arr.T)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
shape: (2, 3)
dimension: 2
size: 6
data type: float64
the transfered matrix of the original: [[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]



### 3. Creating ndarray

In [20]:
#method 1 basic method
#arr=np.array([1,2,3])
list1=[1,2,3]
arr=np.array(list1,dtype=np.float64)
print(arr)

[1. 2. 3.]


In [19]:
# copy
arr1=np.copy(arr)
print(arr1)
arr1[0]=4
print(arr1)
print(arr)

[1 2 3]
[4 2 3]
[1 2 3]


In [22]:
#method 2 predefined shape
# all 0
arr1=np.zeros((2,),dtype=int)
print(arr1)
arr2=np.zeros((2,3),dtype=int)
print(arr2)

[0 0]
[[0 0 0]
 [0 0 0]]


In [23]:
# all 1
arr3=np.ones((5,8),dtype=int)
print(arr3)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [25]:
# uninitialized
arr=np.empty((4,3))
print(arr)

[[9.36952153e-312 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 3.14573925e+097 3.60189510e+175]
 [3.40791583e+175 5.92829578e-062 2.48921072e+180]
 [4.28007013e-033 5.70450456e-066 5.93991899e-038]]


In [27]:
# full
arr=np.full((3,4),2025)
print(arr)
arr1=np.zeros_like(arr)
print(arr1)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [4]:
 # method 3 data range

# arithmetic sequence
arr=np.arange(1,10,2) #(start,end,step)
print(arr)

# equal space
arr1=np.linspace(0,10,5) #(star,end,portions)
print(arr1)

# log space sequence
arr2=np.logspace(0,4,2,base=2) #(start,end,portions,base of log)
print(arr2)
arr3=np.logspace(0,4,3,base=2)
print(arr3)

[1 3 5 7 9]
[ 0.   2.5  5.   7.5 10. ]
[ 1. 16.]
[ 1.  4. 16.]


In [5]:
# method 4 matrix
# identity matrix
arr=np.eye(3,dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [7]:
# diagonal matrix
arr=np.diag([1,2,3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [8]:
# method 5 random number
# random float between 0 and 1 (uniform distribution)
arr=np.random.rand(2,3)
print(arr)

[[0.04765562 0.61724706 0.32753151]
 [0.89086764 0.56798761 0.45022296]]


In [9]:
# random float in assigned range
arr=np.random.uniform(3,6,(2,3))
print(arr)

[[4.23943465 3.99250165 4.1111592 ]
 [4.54009876 5.95181829 5.05496224]]


In [10]:
 # random integer in assigned range
arr=np.random.randint(3,6,(2,3))
print(arr)

[[4 3 3]
 [5 3 4]]


In [11]:
 # random in normal distribution (from -3 to 3)
arr=np.random.randn(2,3)
print(arr)

[[ 0.70804245  0.22301005  1.02571308]
 [-0.3540904  -1.30620228 -1.81785824]]


In [15]:
# random seed
np.random.seed(20)
arr=np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]



### 4. ndarray data type
bool
int
uint
float
complex

In [16]:
arr=np.array([1,0,2,0],dtype='bool') # or np.bool
print(arr)

[ True False  True False]


In [20]:
arr=np.array([1,0,127,0],dtype=np.int8)
print(arr)

[  1   0 127   0]



### 5. Index and slice

In [24]:
# 1 dimension array
arr=np.random.randint(1,100,20)
print(arr)

[25 19 94 34 79 43 95  4 19 71 53 23 15  5 28 76  9  7 27 80]


In [29]:
print(arr[0])
print(arr[:])
print(arr[2:5])
print(arr[slice(2,5)])  #(start,end,step)
print(arr[(arr>10) & (arr<70)])   # bool index


25
[25 19 94 34 79 43 95  4 19 71 53 23 15  5 28 76  9  7 27 80]
[94 34 79]
[94 34 79]
[25 19 34 43 19 53 23 15 28 27]


In [30]:
# 2 dimension array
arr=np.random.randint(1,100,(4,8))
print(arr)

[[83 79 11 34 86 18 41 83]
 [43 61 85 31 37  9 49 20]
 [49 96 54 11 39 10 61 61]
 [24 53 97 77 79 96 55 82]]


In [32]:
print(arr[1,3])
print(arr[1:3,2:4])
print(arr[arr>50])
print(arr[2][arr[2]>50])   #filter row
print(arr[:,3][arr[:,3]>50])

31
[[85 31]
 [54 11]]
[83 79 86 83 61 85 96 54 61 61 53 97 77 79 96 55 82]
[96 54 61 61]
[77]



### 6. ndarray calculation

In [5]:
# arithmatic calculation (different from lists)
# 1 dimensional
a=np.array([1,2,3])
b=np.array([4,5,6])
print('a+b=',a+b)
print('a-b=',a-b)
print('a*b=',a*b)
print('a/b=',a/b)
print('a^2=',a**2)

a+b= [5 7 9]
a-b= [-3 -3 -3]
a*b= [ 4 10 18]
a/b= [0.25 0.4  0.5 ]


In [9]:
# lists
c=[1,2,3]
d=[4,5,6]
print('c+d=',c+d)
sum=[]
for i in range(len(c)):
    sum.append(c[i]+d[i])
print('Adding the corresponding element in list c and d:',sum)

c+d= [1, 2, 3, 4, 5, 6]
Adding the corresponding element in list c and d: [5, 7, 9]


In [10]:
# 2 dimensional
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[7,8,9],[1,2,3]])
print('a+b=',a+b)
print('a-b=',a-b)
print('a*b=',a*b)
print('a/b=',a/b)
print('a^2=',a**2)

a+b= [[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
a-b= [[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
a*b= [[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
a/b= [[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
a^2= [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [12]:
# array and scalar calculation
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[7,8,9],[1,2,3]])
print('a+3=',a+3)
print('a*3=',a*3)

a+3= [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
a*3= [[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [13]:
# broadcasting: 1.shape/dimension of array 2. test if suit criteria
# same dimension: same or 1 -> then broadcast
a=np.array([1,2,3])          #1*3
b=np.array([[4],[5],[6]])    #3*1
print('a+b:',a+b)
'''
a  ->   a'
1 2 3    1 2 3
         1 2 3
         1 2 3

b   ->   b'
4         4 4 4
5         5 5 5
6         6 6 6
'''

a+b [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [15]:
# matrix calculation
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a*b)
print(a@b)   # product of two matrices
'''
a
1 2 3
4 5 6
7 8 9

b
4 5 6
7 8 9
1 2 3
'''

[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


'\na\n1 2 3\n4 5 6\n7 8 9\n\nb\n4 5 6\n7 8 9\n1 2 3\n'

## 2.3 numpy functions


### 1. math functions

In [18]:
# square root
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr=np.array([1,25,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [19]:
# exponential calculation
print('e^1=',np.exp(1))  #e^1

2.718281828459045


In [20]:
# logarithm calculation ln(x)
print('ln(2.718281828459045)=',np.log(2.718281828459045))

ln(2.718281828459045)= 1.0


In [24]:
# triagonal functions
print(np.sin(np.pi/2))   #np.pi=constant pi
print(np.cos(np.pi))

1.0
-1.0


In [25]:
# absolute value
arr= np.array([1,-2,-3,1,0])
print(np.abs(arr))

[1 2 3 1 0]


In [26]:
# a^b
print(np.power(arr,2))

[1 4 9 1 0]


In [28]:
# digit round
print(np.round([3.2,4.5,4.51,8.1,9.6]))

[ 3.  4.  5.  8. 10.]


In [29]:
# ceil and floor operations
arr=np.array([1.6,25.1,81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [30]:
# detect empty data point
np.isnan([1,2,np.nan,3])

array([False, False,  True, False])

### 2.statistic functions

In [32]:
arr=np.random.randint(1,20,8)
print(arr)

[ 1 10 10 12  5  8  9 18]


In [33]:
# sum
print(np.sum(arr))

73


In [34]:
# mean
print(np.mean(arr))

9.125


In [35]:
# median
print(np.median(arr))

9.5


In [36]:
# standard variation and square variation
print(np.var(arr))
print(np.std(arr))

21.609375
4.648588495446763


In [39]:
# find maximum and minimum
print(arr)
print(np.max(arr),np.argmax(arr))    #np.argmax() find index of max
print(np.min(arr),np.argmin(arr))

[ 1 10 10 12  5  8  9 18]
18 7
1 0


In [48]:
# percentile
print(np.median([1,2,3]))
np.random.seed(0)
arr=np.random.randint(0,100,4)
print(arr)
print(np.median(arr))
print(np.percentile(arr,25))

2.0
[44 47 64 67]
55.5
46.25


In [50]:
# accumulated sum and product
arr=np.array([1,2,3])
print(np.cumsum(arr))
print(np.cumprod(arr))

[1 3 6]
[1 2 6]


### 3.compare functions

In [53]:
# greater?
print(np.greater([3,4,5,6,7],4))
# less?
print(np.less([3,4,5,6,7],4))
# equal?
print(np.equal([3,4,5,6,7],4))
print(np.equal([3,4,5],[4,5,5]))

[False False  True  True  True]
[ True False False False False]
[False  True False False False]
[False False  True]


In [58]:
# and
print(np.logical_and([0,0],[1,1]))
# not
print(np.logical_not([1,0]))
# or
print(np.logical_or([1,0],[0,0]))
# any(at least one true)
print(np.any([0,1,2,3]))
# all true?
print(np.all([0,1,2]))

[False False]
[False  True]
[ True False]
True
False


In [62]:
# self-defined
# (condition,valid,invalid)
arr=np.array([1,2,3,4,5])
print(np.where(arr>3,arr,0))
print(np.where(arr>3,1,0))
score=np.array([60,75,30,50,100])
print(np.where(score>=60,'pass','fail'))

[0 0 0 4 5]
[0 0 0 1 1]
['pass' 'pass' 'fail' 'fail' 'pass']


In [64]:
# nested
print(np.where(
    score<60,'fail',np.where(
        score<80,'pass','excellent'
    )
))

['pass' 'pass' 'fail' 'fail' 'excellent']


In [67]:
# select
# np.select(condition,return)
print(np.select([score>=80,(score>=60)&(score<80),score<60],['excellent','pass','fail'],
                default='unknown'))

['pass' 'pass' 'fail' 'fail' 'excellent']


In [70]:
# sequence functions
arr=np.random.randint(1,100,20)
print(arr)
# print(arr.sort())   # change arr
# print(arr)
print(np.sort(arr))
print(arr)
print(np.argsort(arr))   #print sorted index

[33 32 75 24 36 76 56 29 35  1  1 37 54  6 39 18 80  5 43 59]
[ 1  1  5  6 18 24 29 32 33 35 36 37 39 43 54 56 59 75 76 80]
[33 32 75 24 36 76 56 29 35  1  1 37 54  6 39 18 80  5 43 59]
[10  9 17 13 15  3  7  1  0  8  4 11 14 18 12  6 19  2  5 16]


In [71]:
# exclude repetition
print(np.unique(arr))

[ 1  5  6 18 24 29 32 33 35 36 37 39 43 54 56 59 75 76 80]


In [73]:
# concat
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.concatenate((arr1,arr2)))

[1 2 3 4 5 6]


In [76]:
# split
print(np.split(arr,4))
print(np.split(arr,[6,12,18])) #(index want to split)

[array([33, 32, 75, 24, 36], dtype=int32), array([76, 56, 29, 35,  1], dtype=int32), array([ 1, 37, 54,  6, 39], dtype=int32), array([18, 80,  5, 43, 59], dtype=int32)]
[array([33, 32, 75, 24, 36, 76], dtype=int32), array([56, 29, 35,  1,  1, 37], dtype=int32), array([54,  6, 39, 18, 80,  5], dtype=int32), array([43, 59], dtype=int32)]


In [77]:
# reshape array
print(np.reshape(arr,[4,5]))

[[33 32 75 24 36]
 [76 56 29 35  1]
 [ 1 37 54  6 39]
 [18 80  5 43 59]]


## Numpy exercies


### Question 1. Temperature analysis

a series of highest temperatures for a city in one week in celcius degrees: [28,30,29,31,32,30,29]
- claculate the average, highest, and lowest temperature
- find the days that have temperature over 30 degrees celcius

In [89]:
temp=np.array([28,30,29,31,32,30,29])
print('The average temperature is:%.3f'%np.mean(temp))
print('The highest temperature is:',np.max(temp))
print('The lowest temperature is:',np.min(temp))
print('The days that have temperature over 30 degrees:',len(temp[temp>30]))
print('The days that have temperature over 30 degrees:',np.cumsum(np.where(temp>30,1,0))[-1])    #or print(np.count_nonzero(temp>30))

The average temperature is:29.857
The highest temperature is: 32
The lowest temperature is: 28
The days that have temperature over 30 degrees: 2
[False False False  True  True False False]
The days that have temperature over 30 degrees: 2


### Question 2. Score analysis
5 students score [85,90,78,92,88]

-calculate the mean, median, standard variation

-turn the score into full score=10

In [94]:
score=np.array([85,90,78,92,88])
print('The scores from small to large:',np.sort(score))
print('The mean of the scores is:',np.mean(score))
print('The median of the scores is:',np.median(score))
print('The standard variation of the scores is:%.3f'%np.std(score))
print('The score with full score=10 is',score/10)

The scores from small to large: [78 85 88 90 92]
The mean of the scores is: 86.6
The median of the scores is: 88.0
The standard variation of the scores is:4.883
The score with full score=10 is [8.5 9.  7.8 9.2 8.8]


### Question 3. Matrix calculation

A=[[1,2],[3,4]] B=[[5,6],[7,8]]

-calculate A+B and A*B

-calculate the dot product of A and B

In [3]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print('A+B=',A+B)
print('A*B=',A*B)
print('The dot product of A and B is:',A@B)
print(np.dot(A,B))

A+B= [[ 6  8]
 [10 12]]
A*B= [[ 5 12]
 [21 32]]
The matrix product of A and B is: [[19 22]
 [43 50]]


### Question 4. Random number

Generate a (3,4) shape random array, with range[0,10)

-find the largest in each column and smallest in each row

-substitute every odd number with -1

In [14]:
np.random.seed(0)
arr=np.random.randint(0,10,(3,4))
print(arr)
# for i in range(3):
#     print(f'The largest in {i}th row:',np.max(arr[i,:]))
print('The smallest in each row:',np.min(arr,axis=1)) #axis=0-> column axis=1-> row
print('The largest in each column:',np.max(arr,axis=0))
print(np.where(arr%2==0,arr,-1))
# arr[arr%2==1]=-1
# print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
The smallest in each row: [0 3 2]
The largest in each column: [7 9 7 6]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


### Question 5. Reshape array

create a one dimensional array with elements from 1 to 12, rearrange it into a (3,4) matrix

-calculate the sum of each row and the average of each column

-convert the matrix into 1 dimensional array

In [5]:
arr=np.arange(1,13)
arr=np.reshape(arr,(3,4))
print(arr)
print('Sum of each row equals to:',np.sum(arr,axis=1))
print('Mean of each column equals to:',np.mean(arr,axis=0))
arr=np.reshape(arr,(12))
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sum of each row equals to: [10 26 42]
Mean of each column equals to: [5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### Question 6. Boolean indexing

Generate a (5,5) random matrix with range [0,20)

-find all elements larger than 10

-convert all elements larger than 10 into 0

In [11]:
arr=np.random.randint(0,20,(5,5))
print(arr)
print('All elements larger than 10 are:',arr[arr>10])
#print(np.where(arr>10,0,arr))
arr[arr>10]=0
print(arr)

[[ 2 15 15  2  0]
 [12 10  3  7  3]
 [ 4 10 18  8  9]
 [ 3 15 15  6 11]
 [ 9 17  0 10 14]]
All elements larger than 10 are: [15 15 12 18 15 15 11 17 14]
[[ 2  0  0  2  0]
 [ 0 10  3  7  3]
 [ 4 10  0  8  9]
 [ 3  0  0  6  0]
 [ 9  0  0 10  0]]


### Question 7. Statistics

A company's sales in six month are [120,135,110,125,130,140]

-calculate the sum,mean, and squared variation

-find the months that has the highest sales, and the lowest sales

In [13]:
sales=np.array([120,135,110,125,130,140])
print('The total sales is:',np.sum(sales))
print('The mean is',np.mean(sales))
print('The squared variation is:',np.var(sales))
print('The month that has the highest sales:',np.argmax(sales)+1)
print('The month that has the lowest sales:',np.argmin(sales)+1)

The total sales is: 760
The mean is 126.66666666666667
The squared variation is: 97.22222222222223
The month that has the highest sales: 6
The month that has the lowest sales: 3


### Question 8. Array operations

A=[1,2,3],B=[4,5,6]

-Combine A and B horizontally

-Combine A and B vertically

In [16]:
A=np.array([1,2,3])
B=np.array([4,5,6])
print('Horizontal concat:',np.concatenate([A,B]))
C=np.concatenate([A,B])
print('Vertical concat:',np.reshape(C,(2,3)))

Horizontal concat: [1 2 3 4 5 6]
Vertical concat: [[1 2 3]
 [4 5 6]]


### Question 9. Unique value

array=[2,1,2,3,1,4,3]

-Find the unique value in this array and sort

-Find the counts of all the unique values

In [19]:
arr=np.array([2,1,2,3,1,4,3])
C,counts=np.unique(arr,return_counts=True)
print('The unique values in the array are:',C)  #automatically sequence from small to large
print('The counts of each unique number are:',counts)
# or:
# d=[]
# for i in range(len(c)):
#   d+=len(arr[arr==c[i]])
# print(d)

The unique values in the array are: [1 2 3 4]
The counts of each unique number are: [2 2 2 1]


### Question 10. Comprehensive problem

A store's sales for five days are: [20,25,22,30,28]

its costs are: [15,18,16,22,20]

-Calculate the daily profit

-Calculate the mean and standard variation of the profit

-Find the number days that have the highest profit

In [9]:
sale=np.array([20,25,22,30,28])
cost=np.array([15,18,16,22,20])
profit=sale-cost
print('The profits are:',profit)
print('The mean of the profit is:%.3f'%np.mean(profit))
print('The standard variation of the profit is:%.3f'%np.std(profit))
print('The number of days that has the highest profits is:',len(profit[profit==np.max(profit)]))

The profits are: [5 7 6 8 8]
The mean of the profit is:6.800
The standard variation of the profit is:1.166
The number of days that has the highest profits is: 2
